// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PublicTransportAPI.Models
{
    public partial class Linha
    {
        public Linha()
        {
            TbLinhaParada = new HashSet<LinhaParada>();
            TbVeiculos = new HashSet<Veiculo>();
        }

        public long LinhaId { get; set; }
        public string LinhaNome { get; set; }

        public virtual ICollection<LinhaParada> TbLinhaParada { get; set; }
        public virtual ICollection<Veiculo> TbVeiculos { get; set; }
    }
}