// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PublicTransportAPI.Models
{
    public partial class TbLinha
    {
        public TbLinha()
        {
            TbLinhaParada = new HashSet<TbLinhaParadum>();
            TbVeiculos = new HashSet<TbVeiculo>();
        }

        public long LinhaId { get; set; }
        public string LinhaNome { get; set; }

        public virtual ICollection<TbLinhaParadum> TbLinhaParada { get; set; }
        public virtual ICollection<TbVeiculo> TbVeiculos { get; set; }
    }
}