// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PublicTransportAPI.Models
{
    public partial class TbLinhaParadum
    {
        public long LinhaParadaId { get; set; }
        public long FkLinhaId { get; set; }
        public long FkParadaId { get; set; }

        public virtual TbLinha FkLinha { get; set; }
        public virtual TbParadum FkParada { get; set; }
    }
}