// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PublicTransportAPI.Models
{
    public partial class TbParadum
    {
        public TbParadum()
        {
            TbLinhaParada = new HashSet<TbLinhaParadum>();
        }

        public long ParadaId { get; set; }
        public string ParadaNome { get; set; }
        public double ParadaLatitude { get; set; }
        public double ParadaLongitude { get; set; }

        public virtual ICollection<TbLinhaParadum> TbLinhaParada { get; set; }
    }
}