// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PublicTransportAPI.Models
{
    public partial class Veiculo
    {
        public Veiculo()
        {
            TbPosicaoVeiculos = new HashSet<PosicaoVeiculo>();
        }

        public long VeicId { get; set; }
        public string VeicNome { get; set; }
        public string VeicModelo { get; set; }
        public long FkLinhaId { get; set; }

        public virtual Linha FkLinha { get; set; }
        public virtual ICollection<PosicaoVeiculo> TbPosicaoVeiculos { get; set; }
    }
}